/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElRow: typeof import('element-plus/es')['ElRow']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Hellowrold: typeof import('./src/components/hellowrold.vue')['default']
    HelloWrold: typeof import('./src/components/HelloWrold.vue')['default']
    ICarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
    IconMdiAccountBox: typeof import('~icons/mdi/account-box')['default']
    IMdiAccount: typeof import('~icons/mdi/account')['default']
    IMdiAccountBox: typeof import('~icons/mdi/account-box')['default']
    IMidAccount: typeof import('~icons/mi/d-account')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
